(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[0,0,1200,800]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib._45 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



// stage content:
(lib.งาน51 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AF6psQgzgTg3gOIhclQIgwEgQiyhWisgnQjTgwjIAVQgcADgdAEQiBDoANDwQAEBLASBLQAPBDAbBDIh3jZQAih/gMiIQgHi9hYiOIA9jdQBMBtCsBFQBBhkC/hTQBQh7CChpIg1CFIBThBIgtBnQKNgkDrLFQA4A/CdgKQhHG9lZDXQDYjagImDQgXgWgYgVQAKDZhPCqQi9GYiymMQAyEVC8ADIAlgfAodofQgvh/CFhKQB/AKAKBsQALB+hYAqQhpAWgphrgAp1tVQjIEaCPD9QCGDIEDh4QCziIAIkaIA6BYQghElhtBaQiJCMjigwQiWg8hjjdAAOnXQgkEIijCLQioCpj4hvQhsgvhHinArihaQDBGOFjBKQBcjcDhDcQCFiVBQB0ICKh0AIrkbQAAA2geAlQgeAmgrAAQgqAAgegmQgeglAAg2QAAg1AegmQAegmAqAAQArAAAeAmQAeAmAAA1gAJfn1QhohJh9guQiFCogSEwQAFA2AIAvAAOnXIAeAtIAAhsAgwo4IA+BhAJfn1QAjEdhiCzQhhCxjPi7AEQL4QAJgqgIgyQgJgxgYg5QCUgegwi3ABiHPQgDAeAMAWQASAlA8APQAeAAAZgFABiHPQAUgjAJguQgZAugEAjgAh+IbQAZARAkAIQA3gHAngXQAsgZAZguAhaK8QAEA/gOA0QBhguBlgMQBVgKBZANIgjE8IiyAeIg5C2QgpBOhHgMQikg1BWjDIBYkjAh+IbQAeBXAGBKQDrhkCABEAAdIWIBOgTAhwSYIBwAAQgRBRgtAOQg7gTAJhMgABrSGQgoghBzAhQACBKg3gJQg3gbAhgmgABiL1IgnFdQhxBDiGhDAKkm+QghgdgkgaAjas6IBwCqAi+F+QgIBuBIAvAACUIQAjA6A3gCQCPgKACkC");
	this.shape.setTransform(500.025,264.2085);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2DA726").s().p("AgbLQQDshkB/BEQAIAygIAqQhZgOhWALQhmAMhfAuQAOg1gFg+gACiHjQgDAeALAWIhOATQAsgaAagtgAEwgbQDOC7BiixQBhizgjkdQAkAaAiAcQAKDZhPCrQhgDOhdAAQhbAAhXjCgAnqhJQiVg9hkjcQgNjwCCjoQAcgFAdgDQjJEaCQD+QCFDIEEh4QCyiIAIkaIA5BYQggElhtBaQhmBoiYAAQg0AAg5gMg");
	this.shape_1.setTransform(493.6754,262.2375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhHBbQgeglgBg2QABg0AegmQAdgmAqAAQAqAAAfAmQAdAmAAA0QAAA2gdAlQgfAmgqAAQgqAAgdgmg");
	this.shape_2.setTransform(545.25,235.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhuVKQikg1BWjDQCGBDBxhDIg5C2QgjBEg6AAQgJAAgKgCgAg+T3QAtgOARhRIhwAAQgJBMA7ATgAACUIIA5i2ICygeQgCECiPAKIgEAAQg1AAghg4gABrSGQghAmA3AbQA3AJgChKQg5gQgTAAQgTAAAUAQgAACUIgAh+IbQAZARAkAIQA3gHAngXIBOgTQASAlA8APQAeAAAZgFQAYA5AIAxQh/hEjrBkQgGhKgehXgALTmTQgXgWgYgVQghgdgkgaQAjEdhiCzQhhCxjPi7QgIgvgFg2QASkwCFioQB9AuBoBJQhohJh9guQgzgTg3gOIhclQIgwEgQiyhWitgnIgCgBIgNgDIgEgBQiIgdiEAAIAAAAIAAAAQg8AAg7AGIgEABQgcADgdAEQiBDoANDwQAEBLASBLQAPBDAbBDIh3jZQAih/gMiIQgHi9hYiOIA9jdQBMBtCsBFQBBhkC/hTQBQh7CChpIg1CFIBThBIgtBnQKNgkDrLFQA4A/CdgKQhHG9lZDXQDYjagImDgAF8l2QgeAmAAA1QAAA2AeAlQAeAmAqAAQArAAAegmQAeglAAg2QAAg1gegmQgegmgrAAQgqAAgeAmgAquk+QiPj9DIkaIAEgBQA7gGA8AAIAAAAIAAAAQCEAACIAdIAEABIANADIACABIBxCqQgIEaizCIQhhAthQAAQiEAAhUh9gAodofQApBrBpgWQBYgqgLh+QgKhsh/gKQiFBKAvB/g");
	this.shape_3.setTransform(500.025,264.2085);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCCAD").s().p("AECLWQgLgWADgdQAUgjAIgvQgYAugEAkQgaAtgsAaQgnAXg3AHQgkgJgagRQhGgvAHhuQBcjcDhDcIACgBIABgBIABgCIABAAIAAgBIABgBQBHhNA4AAIAAAAIAAAAQAtAAAjAzQgjgzgtAAIAAAAIAAAAQg4AAhHBNIgBABIAAABIgBAAIgBACIgBABIgCABQjhjchcDcQljhJjBmQQgahDgQhCQBICmBsAvQD3BwCoipQCiiLAmkIIhAhhIg6hYIhviqQCrAnCzBWIAwkgIBdFQQA2APAzASQiFCpgREuQAEA3AJAuQAyEWC8ADIiLB1QAwC2iTAeQgZAFgfABQg7gQgTglgADEjWIAAhsIAABsIgeguIAeAug");
	this.shape_4.setTransform(484.8625,243.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_3
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#000000").ss(1,1,1).p("Arpr3QABm+B7kdQDLmtClgQQCQAdARE2Ahf1LQAAADgBADIAEAPAhoztQgIBDgMBAAhg1FQgCAbgCAaAh9xjQgHAjgJAhIAAAAAiOwZQAAACgBAAAk7puIANAEQCmA4B2CcIhqASIjgAkIhihLAlJpyQAAAAAAAAQAHACAHACAiPwVQg7Dph/C6Qiig4ijAvAshrqQAOgIARgEQAOgEALADQA2AKARB5IAHACIAIgGIAFgDQgKADgKAEQAIgCAHgCQC3gjCTApArVpqQAdgGAdgCQDGgoCaAsArVpqQAagGAZgEAnvlzIAxg4IhhhMIAwCEIAOAnIhQAhIh8AwQg8GRCmCbQDCC2DCg9QC5g+BTj2QAzifhGjgQBxEEhOEuQhdFMkwDIIAABRIhFgoQAZgNAYgPQAHgFAHgEQADgCADgCAA5kLQABABAAABAgSmWQAsBEAfBHgAmLgWQAFiFBsgZQB6ABAGCNQAFCLhtAMQiOgDAFiEgAsSKSQB0B7AZjVAoxkrQheDeA1CVQBWD/D4AXQDpgKA/lQQgFkviThZAkwOOQB5BJgvCaQgUAhgUAaQBICXBrhnQALC4h8B6IgIgMIg9hfAnOQrIAJAwQAKgeAQgkQANg7gogjIgkgjgAqvUxIAAAAIAAEeQAmAjAhgWQAoAjAZgFIAEAdQB/AJB5guQA/B5gqBtQgcAyghAGQhxgHgphfQgmg8gNhHQgCgIgBgIQB6ARB+g2AmiT5QgCgBgBAAQgdgKgLgZQgSgpAahRApFVFIgUAAIAyE1AsXO/QCgAHCNguQA9gUA4geApFVFQg0gOg2gGQhUgJhYANIgdDeIgDAUQA+AoBEAFQAkADAmgIQAYCghXA3QgrANgIgFQg9gJgdh1IAAiJAp7XwIATBsAl0WDIgCgIIjjg2AkuZUIhGjRAjUYCQAJAmhjAsIADAdIAAABAnEbHIBogXQAfA5gfAvQhUAagUhrgAkrZxIhJjuAl2V7IjPg2AkOSsQhNBhhHgUAl2V7IgsiCAUJDgQAxhUBGBEQA2AzgzA+QgkAtg4gXQhPgjAxhUgAxCmlQjwj2BloYQB8maCZgyQCTAiAOJjIgKEQA0DjRQAfgtAlgqQAXgbAagaIAygxQANgMANgLQBNhEBTgvQAWgMAXgLQAAgBAAgBQAMiPBIgqAuioYQAWgNAXgMQBRgpBPgQAqtj7IivBFIg4jgIhdEyIhSAyIhSAxIgKhQIgKhQIgaBUIgvCUIg4AyIhAA6IglAhIgFgOQAAgBAAgBQAajMB3jJQAmhBAwhAAy/koQCRidCMhTAx0FkQgTiDBQglQBWgZAeByQAeByhDAlQhjAogphwgA2PDUIgIAHQABgLACgKQAQjcCBi7A2bEQQABgbADgaAueIwQgIBMgUA0QhFCwjThbQjRi+AUlzAxDgyQDLEngmE7AzDhNIAkgEA0qB5QA2K0FWj9A1qCzQAAFKCKCGQCCCTCkhmAuZOxQA0AJAzADQgwAygFA3IAmCDQgsBPg4gRQgNgEgNgIQhQgcAGieQAkhgBMgQgAtFS7IgWB6AtBSpIgEASQC5gTC/AtAulTnQgjB+hLhaQABCCBoBbIAyArAsoQeIgZCLAtPZoIBEAbQAcAphGAdQg1goAbg5gAuqXoIAniAAzSMFQB6CDC/ApAqvUxIisAEAsyO9QANABAOABIgRBfIFaANAt1ovQBOgnBSgU");
	this.shape_5.setTransform(404.166,206.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFCCAD").s().p("ACIN2IgDgBQgdgJgLgaQgSgoAbhRQAJgeARglQAMg6gogkIgjgjQA8gTA5geIBEAoQB5BJgvCaQgUAhgUAaQg/BQg8AAQgMAAgNgEgAl6NlQgNgEgNgJQhQgbAHieQAjhgBMgRQA0AJAzAEQgwAygFA3IAmCCQgkBCgsAAQgKAAgKgDgAjsI9IgbgCQgzgEg0gJQi/goh6iEQDTBcBFiwQAUg1AIhLQAmk6jKkoIBSgyIBckyIA5DgICvhFQg9GSCmCbQDBC1DCg9QC5g9BUj2QAzighGjgQBxEEhNEvQheFLkxDIIgGAEIgOAJQgYAPgYANQg5Aeg8ATQh5ApiIAAIgsgBgAieE9QA0gBAQiEIAAgBIABgCIgBACIAAABQgQCEg0ABIAAAAIgBAAQgcAAgogpIAAAAIgDgDIgBgBIABABIADADIAAAAQAoApAcAAIABAAIAAAAgAALt5IBiBLIgyA5g");
	this.shape_6.setTransform(348.6463,245.4605);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF99CC").s().p("ABiNeQg0gPg1gFQhUgJhYANIAWh6QC4gTC/AsQALAaAdAJIADABIArCDgAiBI3IAShfQCfAHCNgvIAcCTgAo4CbQiKiFgBlJIBBg6QA1KzFXj9QgIBMgVA0QhDAqg9AAQhYAAhNhYgABNmeQg1iWBdjfIBRgfIgOgoIAxg5IBiBNIDfglQCVBZAFEwQhAFQjpAKQj4gXhWj/gAEOskQh8BUgSCWQgKC0B+BbQBEAwBbAbQA6AQB8hvQAshXAUhmQAIhrgwhMQhhh+iRAAQguAAgzANg");
	this.shape_7.setTransform(336.1875,255.55);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AC2QHQgmg8gNhHIgCgQQB6ASB9g3QBAB6gqBsQgdAzghAFQhxgGgphggADgOkQATBsBVgbQAegvgeg5gAh9QLQg9gJgdh1IAAiJQA+AoBEAFQAkADAngHQAWCghVA2QghAKgMAAQgFAAgCgCgAiROmQBHgdgcgpIhFgaQgbA4A1AogAigGYIADgSIAZiLIFZANIAKAxQgbBQASApQi/gti3ATgAqGqoIA5gzIAuiVIAlgEIAKBRIBSgyQDKEogmE7QhcBEhHAAQjCAAgnn6gAmTpmQhQAlATCDQApBxBjgoQBDglgehyQgZheg+AAQgOAAgPAEgAGPocQhbgbhDgwQh/haAKi1QASiVB9hVQDSg1CBCmQAwBNgIBrQgVBmgsBXQhrBgg7AAQgIAAgIgCgAEYs5QgECFCOAEQBsgMgFiNQgFiNh6gBQhtAZgFCFg");
	this.shape_8.setTransform(336.5478,287.1074);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhIQDIBngWQAeA4geAwQgRAFgOAAQg5AAgPhXgAnUOlIBFAbQAcAohHAeQg1gpAbg4gAjImRQimicA9mRIB7gxQheDeA2CXQBVD+D4AYQDogLBAlPQgFkwiUhZIBrgSIBLCKIABADQBHDgg0CgQhUD2i5A+QgxAPgxAAQiQAAiRiIg");
	this.shape_9.setTransform(366.2376,277.5797);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#990000").s().p("AlPHlIgCgIIgCgIIgUABQgMAAgGgGQgEgEgBgGQAAgHADgEQACgDAIgFQAHgEAJgCIADgCQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQgBgLAIgGQgEgIAEgHQADgIAIgDIAEgCIAAgGQgBgGAGgFQACgCAJgFQAQgFAGgBQANgBAIAHIAHAIQAXAhAIAnQABAHACADIAFAGQAEAHgEAHQgDAHgKADIgQACQgNABgLADIgQAFIgNACQgLAFgGAAQgJAAgEgHgABsHTIgBAAIgFgBIgPgFIgKgDIgRgBIg8gJQgYgEgMAAIgRABIg6AEQgIABgEgBIgCgBIgBABIgXAGIgHAAQgEACgGAAIgIABQgJAEgFAAIAAAAIgIAEQgLAEgGgIQgEgDgBgFQAAgFACgDQACgEAHgFIAFgDIAAgBQAGgFAGAAIAFAAIAHgDIAAAAIABgHQADgIAIgEIANgEIABAAQABgFAFgGQAWgVAxgaIBQgrQAAgYAPgaQAJgRAWgcIA7hHQgBgFACgFQADgHAKgEIAGgDIAogsQAEgKAFgKQAHgRAFgMQAOgZAUgQIAQgKIABgEQAEgNAGgcIANg5QAMg3AAgcIgBgjQgCgVABgNQACgXAKgkQAPg0AMgUIAQgbIAGgQIAIgPQAGgKAKgEIAGgBQAHgBAEAFQADAEABAMQADBagFAwQgEAtgNAlQgIAagNAVQAJABAGAIIACADQADAHAAAIQgBAJgGALIgJANIgMASIADAAQAJADABALQAAADgDALIgFASIgCAHIABADQACAHgFANIgCAFIABADIAAARIAAABIAAADIgBACIAAAAIgFAHIgDARQgCAKgEAEIAAABIgBAXIgBAEIABACIAAAAIgBAFIgBABIAAABIAAABIAAAAIAAABIgCAEIgBABQABADgCADIgDAEIgCACQABAFgDAIIgJAXIgIAaIgIAgIgDAKIgCAFQABAFgEAIQgIATgGANIgDAEIgCACIgDAIQgGAWgGAMIgDAFQgDALgDAEIgDAGIgIASIgEAGIAAABIgBAEIgCACIgEAHIgDAGQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQgCAEgEACIgOAfIgEAEIgCADIgCAFIgEAFIgBAFQAAADgFAEIgEAEIgCAEIgHANIgEAFIgBACIgCAFIgHAOIgEADIgBABIgCACQgEAEgGAAQgIAAgEgFgAhYGJIAQgCIgFgEQgHACgEAEgAgaF9IgHAGIABAAQAEAAACgBQADgCACgFIgFACgAgEFrIAIgEIAAgGQgEACgEAIgAFfl5IABAFQACAIgEALIgHATQgCAHABAPQAAAOgCAIQgBAFgGALQgFAKgBAGIACACQAOgEABgWQgBgVACgLIAIgTQACgJgBgPQgBgRABgGIAAAAQAAAAgBAAQAAAAgBABQAAAAAAABQgBAAAAABg");
	this.shape_10.setTransform(358.3031,96.4023);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF0000").s().p("AopgYQB8maCagyQCTAiANJiIgJEQQAOgIAQgFQAOgDAMADQAAm9B6keQDLmsClgQQCRAdARE2IgGACQgKAEgGAJIgIAQIgGAQIgQAaQgMAVgPAzQgKAlgCAWQgBANACAWIABAiQAAAdgMA3IgNA5QgGAbgEANIgBAEIgQAKQgUAPgOAbQgGALgGARQgFAKgEALIgoArIgGADQgKAFgDAGQgDAFACAFIg7BIQgWAbgJARQgPAbAAAYIhRArQgxAZgWAWQgFAFgBAFIgBAAIgNAEQgIAEgDAJIgBAGIAAAAIgHADIgFAAQgGABgGAFIAAAAIgFADQgHAFgCAEQgBAEAAAFQAAAFAEADQAGAHALgEIAIgEIAAAAQAFAAAJgEIAIgBQAGAAAEgBIAHgBIAXgGIABAAIACAAQAEABAIgBIA6gEIARgBQAMAAAYAEIA9AKIARAAIAKADIAPAFIAFABIABABQAEAEAIAAQAGAAAEgDIACgCIABgBIAEgEIAHgNIACgGIABgBIAEgGIAHgNIACgEIAEgDQAFgEAAgEIABgEIAEgFIACgFIACgEIAEgEIAOgeQAEgDACgEQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIADgFIAEgIIACgBIABgEIAAgBIAEgHIAIgRIADgHQACgEAEgKIADgGQAGgMAGgVIADgIIACgCIADgFQAGgMAIgUQAEgHgBgFIACgGIADgKIAIggIAIgaIAJgWQADgJgBgFIACgCIADgEQABgCAAgEIABgBIACgDQg8Dph+C6Qijg4iiAvIgUAGQgRh4g1gKQA1AKARB4QgZAFgZAGQhPAQhRApQAMiPBIgqQhIAqgMCPQgXAMgXANQhTAvhNBEQjwj2BloXgAh5IgIACAIIACAHQAEAIAJAAQAGAAALgGIANgCIAQgEQALgEANgBIAQgCQAKgCADgHQAEgHgEgIIgFgGQgCgDgBgGQgIgngXghIgHgJQgIgGgNABQgGAAgQAGQgJAEgCACQgGAGABAGIAAAFIgEADQgIADgDAHQgEAIAEAHQgIAHABAKQABABAAABQAAAAAAABQAAAAAAABQAAAAgBAAIgDACQgJADgHAEQgIAEgCADQgDAFAAAGQABAHAEAEQAGAFAMAAIAQAAIAEAAgACMHNIAFAFIgQABQAEgEAHgCgAC4HOIAHgGIAFgDQgCAGgDABQgCACgEAAIAAAAIgBAAgADeGsIAAAGIgJADQAFgHAEgCgAIVCDIAAgCIAAACgAIWB5IABgEIABgXIAAAAQAEgEACgKIADgTIAFgGQgHAigIAigAInAfIgBgCIACgGQAFgMgCgHIgBgDIACgGIAFgTQADgKAAgEQgBgLgJgCIgDgBIAMgRIAJgNQgIBDgNA/gAI+h4QgGgJgJAAQANgWAIgaIAAAHIgEA1IgCgDgAIhi3QABgGAFgKQAGgLABgGQACgHAAgPQgBgPACgHIAHgSQAEgMgCgHIgBgGQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQgBAGABASQABAPgCAIIgIAUQgCAKABAWQgBAWgOAEg");
	this.shape_11.setTransform(336.5125,88.9625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF6600").s().p("ABrRiIgThsIATBsQghAWgmgjIAAkeIAAAAQA2AFA0APIgUAAIAyE0IgIABQgXAAgigegAFfOJIgCgJIgsiCQBHAVBNhhQBICXBrhoQALC5h8B6IgIgMIg9hgIA9BgQAJAmhjArgAjWPtIAnh/IgnB/QhohagBiCQBLBaAjh+QA4ARAshQIgmiCQAFg3AwgyIAbACIgRBfIgZCKIgEATIgWB5IgdDegAEFIwIgciTIAkAjQAoAkgNA6QgQAlgKAegAFeFsQAZgNAYgPIAOgJIAGgEIAABRgArAkzIAAgCQAajNB3jJQAfgtAlgqQCRidCMhTQAWgMAXgMQBOgmBSgUQAcgGAdgCQDGgoCaAsIANAEQCmA4B2CcIhqASIjgAkIhihMIhhhLIAwCEIAOAnIhQAgIh8AxIiuBFIg4jgIhdEyIhSAyIhSAxIgKhQIgKhQIgaBUIgvCVIg4AyIhAA6IglAhg");
	this.shape_12.setTransform(331.7625,257.4548);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5}]}).wait(1));

	// Layer_2
	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#000000").ss(1,1,1).p("AmpsAQBnghB4hXICfE7IAAAAQAQARASAQQAaAaAfAWQCjB4EHA7QAZAGAZAFQhbhkgHirAFvsYQAjg/BAAkIgOAiAE5r5QAYgbAbgEQACAAABAAQAkgEAoAjQCXksD+BXQAOAEAPAGAHBsHIgGAOQBVA8hmCAAE5r5Qg8DJCtgNANQvOQC9BchLCDQjQDYgNFgQiLgihOhVAk6wPQANgBAMAAQAJAAAKAAQAIABAHAAQFjAXDVD/AlgxhIAmBSAlgxhQBJgYAJBpArFtYQlrgoB3miQAfB8BGhAQCBjvCUAQQDKAtAVE3QiBgtAACiArhs6QAOgQAOgOQBkhmCAguQBOgcBZgHAqPsEQgRgHgRgKQgYgQgYgVQgNAUgNAUQAAAAAAABQgBABAAABQixEcAmENQAuFFFrExQAZAMAYALQAbAMAaAKQgNAsgNAsQgVBLgSBJQgDALgCAMQgSBKgOBIQBdAoBigBIAAAYIAAAHIAAEyQh5Arh5geQgOC1B+A3QByAaAeiaQAFhJgTgwAmpsAQACB3gLBlQgIhYhDADQiyApA0CdQA0CdB8iFQgkCWhNBhQgZAhgeAaQilCHhvkEAmpsAQiBAphlgtQjpJyE8gSAqxsVQhoCCgqDlQgPCvBBBMQBCBMBcgCAnzgHQBMCFBMiFAm9GnQgFAKgFAIAnIG7QgyBVgEAZQgIBFA9A7AkvN5QATgBAUgBQBhgJBlgxQAyCsBFBuAn0UMIB5AAQgDArggAYQhSAYgEhbgAnuNSQgpDQgKC1AAniCQgNiABtgmQBUgRAuBMQAmA/gfBeQgfBWhZABQhkgJgNiAgAgJocQhxBcg0DDQggDRBDB0QBaDHC7ApQByASBqg1QBYgvA+h0QBmjfhWjBAgro9QhaBXhHCSQhDCXAqDkQBtDoBAAnQDSCEDChSQBrh/A1h3AAwnsQjxDOBrFKQD0FyEdkzQBvjNhQjXAiHH7QAlADAjgBQAyBMgMA6QgSBFguAdAiHH7QAEAYAEAYQAOBTARBKQADAPAEAOQALAuAMAqAhMUAIBvhBQALA9gmAcQgvAmglg+gAigTcQCHAFBOiKAigTcQAuC1CRAMQBKgXAThPQAQh5hXhnAg/H9QDegEC9iRAmIG9QCGA0B7AKAmyokQgJBJgQBAAmiIVQCSBNCRg3AnOLAQCeB+DQh2AkIN3IBoFl");
	this.shape_13.setTransform(186.4768,252.4147);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AkrQAIB5AAQgDArggAYQgRAFgOAAQg0AAgDhIgAB8P0IBwhBQALA9gmAcQgSAOgRAAQgbAAgXgmgACQAqQhAgnhsjnQgqjmBDiWQBGiSBahXIAAAAQAQARASAQQhxBcg0DDQgfDRBCB1QBaDGC8ApQByASBqg1QBYguA+h0Qg1B2hrB/QhKAfhNAAQh8AAiChRgAq+nyQgmkNCxkcIABgDIABAAIAagpQAXAWAZAPQhpCCgqDmQgPCuBBBNQBCBMBcgCQg4AugzAAQhgAAhJirg");
	this.shape_14.setTransform(166.3636,279.2426);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFCCAD").s().p("AC1MSQgRhKgOhTIgIgxQh8gKiEgzIg1gWIA1AWIgaBYQgVBLgSBJQg+g7AJhFQADgZAzhVQgCAGACAFQACAGAHADIAEACQAFAIAKgDIADAAIAFABQAKADAHgIIABgBQAFgIgEgHIgCgDQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIgXgKIgPgCIAAABQgGAAgFAFIgBABIgBABIALgSIgxgXQlrkxgulFQBvEECliHQAdgbAaggQBMhhAliWQAQhAAIhJQAMhlgCh3QBmghB4hXICfE7QhbBXhGCSQhDCXApDkQBuDoA/AnQDUCEDChSQi9CRjfAEIgFAAIgFAAIAAAAIgBAAQgbAAgcgCIgGgBIAGABQAcACAbAAIABAAIAAAAIAFAAIAFAAQAyBMgMA6QgSBFguAdIgHgdgACkJKQgDAAgDABQgEADgCAGQgDAFACAFQABAHAFADIAHACIAFABIAggCIABAAQAJADAGgHIABgBIABgBIABgCQADgFgCgGIgBgCIgCgDQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIgIgFQgDgBgHAAIAAAAQgFAAgEACIAAABIgRAAIgDgCIgFgBIgBABgAhFBCQgmBDgmAAQgmAAgnhDQAnBDAmAAQAmAAAmhDg");
	this.shape_15.setTransform(158.7,245.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#999999").s().p("AgND6IgDgBIgDgEIgBAAIAAgBIgBAAIgBgGIgBAAIAAgDIABgDIAAAAIAAgCIABAAQgCgDAAgGIABgBQAAgEACgCIABgBQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIACgCQADgCAFAAIABAAIAHAAQAFABADADIABABIABABIABACIACAEIAAAAIAAACIABABIAAABIAAAFIAAABIAAAAIABAAIAAACQADAGgDAFIgBACIAAAAIgBACIgBABQgCACgFACIgOAAgAgyD5IhPgNIglgJIgkgKQgLgDgDgEQgEgEAAgJQgBgJAEgFQADgEAJgBQAFAAAJADQA1AQAWADQARADAiADIATACIAKADQAIAEACAOIAAAGQgBAJgGAEQgDACgFAAIgJgBgAAdDqQgDgCgCgDIgCgCIAAAAIgBgCIAAAAIgCgGIAAAAIAAgDIAAgCIAAgBIABgDIABAAQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABgBIAEgDIACgBIAIgCIAAAAIAFAAIACABIAHgBIAAgBIABABIAEgDIAGgBIAAAAQAEAAAEACQAFgFAJgCIBOgVIAXgKIANgGQAIgCAFAGQAFAGgBAIIAAAAIADAEQADAIgEAHQgDAFgNAFQgTAHgKACIgUACIgtAMIgJACQgCACgGABQgTAFgbABQgKAAgFgCgACkiLIgHgDQgGgDgBgGQgCgFADgGQACgFAFgDQACgCADAAIACAAIAEABIAEABIAQAAIAAAAQAEgCAFAAIABgBQAGAAADACIAIAFQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIACADIABADQACAGgDAFIAAABIgBACIgCABQgGAGgJgDIAAAAIghACgABKiVIgWgHIgRgDQgJgCgRgFIgagHIgSgDIgSgFIgRgHQgRgHgNgDQgMgDgFgFQgGgIAEgIQAEgIAJgBQAGgBAKAEIAlAOQAJAEAIACIAVAEIAdAIQAUAGAKACIASADIAPAFQASAGAVgBQALAAADABQAIAFABAIQABAJgIAFQgEACgJAAQgeAAgPgEgAiPjVIgEgBIgEABQgJACgGgIIgEgCQgHgCgCgGQgCgFACgHIAAgBIABAAIABgCIABgBQAEgFAGAAIABAAIAPACIAWAKQAAAAAAAAQAAABABAAQAAAAAAAAQAAAAABAAIACADQAEAHgFAIIgBACQgFAFgGAAIgGgBg");
	this.shape_16.setTransform(158.78,320.875);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFBF4").s().p("AkqDHQAJi2ApjOQBeAnBhgBIAAAZQgCgNgHgFIgKgDIgTgCQgjgCgRgDQgWgEg0gQQgJgDgFAAQgJABgDAFQgEAFABAIQAAAJADAEQAEAEAKADIAlAKIAlAJIBPAOQAMACAFgDQAFgEABgKIAAEyQhHAZhGAAQgyAAgygMgABVDMIhnllQBggIBlgxQAzCsBFBtQhLCFiBAAIgKAAgAgKiOIAAACIgBABIAAAEIABAAIABAGIABAAIAAABIABAAIABACQACADAEACQADADALAAQAagBAUgFQAFgCADgCIAIgCIAtgMIAVgCQAKgBATgHQAMgGAEgFQAEgHgEgHIgDgFIAAAAQACgIgGgFQgFgGgIACIgNAGIgWAJIhPAVQgJADgFAEQgDgCgEAAIAAABIgGABIgEACIgCAAIAAAAIgGABIgCAAIgFgBIAAABIgHABIgDABIgEAEQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAAIgBACg");
	this.shape_17.setTransform(161.825,356.4434);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFEAEF").s().p("AheA5Qg0idCxgpQBDgCAIBXQgIBJgQBAQg5A9gpAAQgxAAgdhVg");
	this.shape_18.setTransform(132.3101,203.1683);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#3E97FF").s().p("AjVC3QAOhHAShLQCeB/DPh3IAHAeQALAtAMArQhlAwhhAJQgTACgTAAIgFAAQhfAAhbgngAiIiFIAZhYQCFA0B7AKIAIAwQg8AXg9AAQhUAAhUgtgAhmjVQgJABgEAIQgEAIAGAIQAFAFAMADQANADARAHIARAHIASAFIASADIAaAHQARAFAJACIARADIAWAHQAPAEAeAAQAJAAAEgCQAIgFgBgJQgBgIgIgFQgDgBgLAAQgVABgSgGIgPgFIgSgDQgKgCgUgGIgdgIIgVgEQgIgCgJgEIglgOQgJgDgFAAIgCAAg");
	this.shape_19.setTransform(158.3625,319.0885);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("Ak2RiQh+g3APi1QB4AeB5grQAUAwgGBJQgaCEhXAAQgOAAgRgEgAkjPuQAhgYACgrIh4AAQADBbBSgYgAglN7QCHAFBOiKQBXBngQB5QgSBPhKAXQiTgMgti1gAAuOfQAmA+AvgmQAngcgLg9gAlTFfIAGgXQAShJAVhLQCRBNCRg3QANBTARBKQhjA5hZAAQhfAAhShBgAAkk0QhqlLDyjOQCiB4EHA7QBRDXhvDOQiBCLh6AAQiSAAiGjKgAEDqJQhtAlANCBQANCABjAKQBZgBAfhXQAfhegmg/Qglg/g/AAQgOAAgPAEgAoUxlQBlAtCCgpQACB3gMBlQgIhYhDADQiyApA0CdQA0CdB9iFQglCVhMBiIgSAAQkjAADhpgg");
	this.shape_20.setTransform(174.125,287.7381);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#108DFF").s().p("AETIlQi8gphYjHQhDh1AfjQQA0jDBwhcQAcAZAfAXQjxDOBpFKQD2FxEdkyQBvjOhRjWIAzALQBVDAhlDgQg+B0hYAvQhPAohUAAQgdAAgdgFgAqHA5QhBhMAPiuQAqjmBoiCQAQAKARAIQjoJxE8gSQgaAggeAbIgEAAQhZAAhAhKg");
	this.shape_21.setTransform(172.7087,228.7411);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#1082FF").s().p("AE6BbQAYgbAbgEIADgBIAGAAIABAAIAAAAQAgAAAjAfIABAAIABABIgBgBIgBAAQgjgfggAAIAAAAIgBAAIgGAAQAjg+A/AkIgNAiIAAgCIAAgCIgBgBIAAgCIgBgBQgDgFgGgCIgDAAIgIABIgEADIgCADIgBACIgBACIAAACIAAADIAAACIABADIABACIADADQAFAEAHgBIAEgBIACgBIADgDIgFAPQBUA7hmCAIgUABQiVAAA5i8gAFBBbIgBABIgEAEQgEAEgCAIQgEANgBALIgBAVIAAANIgDAFIAAACIAAAEIgCAEIAAABQgBAJADAGIACABIABACIAAABQAAALABAFIAFAKQAFAMAHAHIACAEQADAIAIABIAEABIACACIARAGIAIADIABAAIASAFIALABIAFAAQAJgBAFgIIABgDIAAgEQAAgHgFgEQAFgDAAgHQAAgHgGgFQgLgDgEgEQgDgDgCgIIgFgTQAEAIAEAEQAIAIAJgBQAIgCADgGQADgGgDgHIgHgIIgFgLIgLgXQgIgRAAgIIAAgIQgBgIgIgEQgFgCgEABQgEgFgHgBIgBgFQgEgGgJgCIgIAAQgMAAgGAJgAlfkNQBJgXAIBpIgTgBIgYACIgmhTIAmBTQhZAGhPAdQABiiCBAsgAmBjVQgzAGgZAKQgJAEgDADQgEAGACAHQADAHAHADQAFABAHgCIAMgEQAOgFAWgDIAlgFIAPgDQALAAAEgBQAKgFgBgKQAAgEgDgEQgDgEgFgBIgKgBgAlGkBQgJAGACALIAEAHIAFAGQACADAAAIIABADIACAEQAEAKAFAEQAIAFAJgFQAIgGgCgJIgDgIIgDgKIgBgEIgCgHIgDgEIgJgMQgFgEgFAAQgEAAgEACg");
	this.shape_22.setTransform(186.4347,167.1533);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#103EF4").s().p("AGNEMIgSgFIgBgBIgJgCIgRgHIgCgBIgEgBQgHgBgEgIIgBgFQgHgHgGgLIgEgLQgCgFAAgKIAAgCIgBgBIgBgCQgEgGABgJIABAAIABgFIAAgDIABgDIACgEIAAgNIABgVQACgLAEgOQACgIADgEIAFgEIAAAAQAJgNARAEQAKACADAGIACAEQAHABADAFQAFgBAFADQAHADABAIIABAJQAAAIAHARIALAXIAGAKIAGAJQADAGgDAGQgDAHgHABQgJACgIgIQgEgFgEgIIAEAUQACAHAEAEQAEADAKAEQAGAEAAAHQAAAHgEAEQAEADABAHIgBAEIgBADQgFAIgIABIgFABIgLgBgAG3BFIgCgCIgCgDIAAgDIgBgBIAAgDIABgDIAAgBIABgCIACgDIAEgDIAIgCIAEABQAFABADAFIABABIABADIAAABIAAABIABACIAAABIgBAAIAAAEIgDAEIAAAAIgDADIgDACIgDABIgDAAQgFAAgFgEgAnGiwQgHgCgCgHQgDgIAFgFQACgEAJgEQAagKAzgGIAigEIALAAQAEABADAEQADAEAAAFQABAKgKAEQgDACgMAAIgOACIglAFQgXADgNAFIgMAFIgIABIgFgBgAkqjMQgFgEgEgJIgCgEIgBgDQgBgIgCgDIgFgGIgDgIQgDgKAKgGQAJgFAIAGIAKAMIACAEIADAHIAAAEIAEALIADAHQABAKgIAFQgEADgEAAQgEAAgEgDg");
	this.shape_23.setTransform(185.2554,168.0413);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFE057").s().p("AK/JBQkHg7iih4QgfgWgcgaQgRgQgQgRIgBAAIiek7Qh4BXhmAhQiCAqhlguQgRgHgQgKQgZgQgXgVIAbgeQBlhlB/guQBPgcBZgHIAYgBIATAAIAQABQFjAXDVD+Qg8DJCsgNQAICrBbBkIgzgLgArTmnQAeB8BGhAQCBjvCVAQQDJAuAWE2QiBgtgBCiQh/AuhlBlQlqgnB3migAj8hxIAAAAg");
	this.shape_24.setTransform(163.5346,163.3016);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFCC52").s().p("AizEeQhbhkgIirQBmh/hUg7QCXktD9BXQC8BchLCEQjPDWgNFhQiKgihOhWg");
	this.shape_25.setTransform(256.9172,193.4949);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13}]}).wait(1));

	// Layer_1
	this.instance = new lib._45();
	this.instance.setTransform(649,13,0.4583,0.5594);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_5
	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#000000").ss(1,1,1).p("AKAk3QAABfgqBDQgqBDg8AAQg7AAgrhDQgqhDAAhfQAAhfAqhDQArhDA7AAQA8AAAqBDQAqBDAABfgAWekSQAABMgsA2QgsA2g9AAQg+AAgsg2Qgrg2AAhMQAAhMArg2QAsg2A+AAQA9AAAsA2QAsA2AABMgAizA5QAABAgeAtQgfAugrAAQgrAAgeguQgfgtAAhAQAAg/AfguQAegtArAAQArAAAfAtQAeAuAAA/gAqVgtQAGDMAoCAQBECmBEAyQAGADAGADQBMAoBQgKQBtgTAOheImwn8gAqWg/QAAAJABAJIgDADAnElTIAahUIAKBQgAxTAiQAABQgwA4QgwA5hFAAQhEAAgxg5Qgwg4AAhQQAAhOAwg5QAxg4BEAAQBFAAAwA4QAwA5AABOg");
	this.shape_26.setTransform(327.525,233.0725);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFCCAD").s().p("AAIgpIAKBPIgjAEg");
	this.shape_27.setTransform(284,194.85);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("ARlQ0QgYgDgUgRQgUgQgHgYQgGgSACghQABgKgBgFQgBgCgJgMQgTgYAFgrQADgYAIgUIAHgSIAGgYQAJglAKgjQAMgrAVg9QAIgZAHgMQALgRATgKQASgKAUgBQgBgcABgOQABgXAIgRICYAAQAFAIABALQAigPAhANQAiAMAOAhQALAbgEAuIgPBkQgJA8gBAnIABAbQgBAPgCALQgGAcgVAUQgKAJgCAGQgCAFABAJQADArgJAXQgIAUgRAOQgRAOgVAEQgVAEgVgHQgVgHgOgPQgPgPgKgcIgNAkQgHAXgHAMQgNAVgXALQgTAJgUAAIgJAAgAizOkQgHgFgEgBIgPAAQgfAFgbgNQgbgNgOgcQgGgPgCgVQgBgNABgZQAAgIgBgDQgBgDgHgHQgPgOgGgTQgHgUAEgTIAAgHQgBgCgFgDQgTgNgKgWQgLgVACgYIgMgCIgEAJQgHALgKAIQACALABANIgBAjIAAAyQgCAcgKATQgNAXgYANQgYALgYgDIgNAFQghAJgggSQgdgSgMghQgIgVABgjQABggAJgXQgOgTgCgYQgBgPADgOIgCgLQgDgbANgWQARggAlgOQAhgNAnACQAdAAAZAIIACABQAFgKAHgIQAPgSAZgIQAKgEALgBIgCAAQAYgCAgAHIA4AMQAVAEBMALQA8AIAjALQAnANAUAUQAPAPAHAVQAGAVgDAWQgCAVgNATQgMASgTALIgHAGQgDAFAEALQAKAYgGAcQgFAbgSATQAOAYAFATQAFAYgKAZQgKAYgVAOQgUAOgaAAIgCAAQgZAAgUgNgAYuAVQgbgEgTgLQgZgNgXgiQgYgogOgTQgJgLgOgPIgYgZQgUgVgVgeQgVgfgFgYQgEgYAJgYQAJgYAUgOQARgLAVgCQAVgDAUAHQAnANAWAmIANAYQAIAOAHAHQAHAIAkAYQAcARAFAUQAVgbAGgjQACgLAAgVIADggQADgQAOgkQAXg9AQg7IARhBQAKgmALgaQAdhFAxgYQAdgOAgAFQAhAGARAYQAKANAEAUQADAMACAYQAFBEACA8QADBQgPAsQgKAggmA6QgmA5gKAhIgIAdQgFARgGALQgHAPgVAVQgXAXgHALIgPAbQgJAQgIAJQgSARgfAHQgUAEgmABQggAAgRgCgAvZgYIgMgHQhEgyhEilQgoiBgGjNIAqgkIGwH8QgOBfhtASQgQABgQAAQg/AAg+gegAL4inIg/gCQgkgBgagHQgggIgZgSQgcgUgLgcIgHgXQgFgOgEgIQgIgPgcgXQgrgigNgeQgJgXAAgqQAAg0gDgPIgHgfQgEgTAAgMQgBgZAPgWQAOgWAYgKQAXgKAaAGQAaAFASASQAOAOAKAaIARAtQAHASAPAcIAXAtQALAYAMAjIAUA7QAFANAFADQAOAIAUgXQAYgaAtgZIBNgrQAMgIBdhGQA+gwAxgQQAPgEAGgDQALgFAFgHQAGgJACgSIAIhGQAEgeAEgOQAGgYALgQQAMgPATgJQASgJAUABQATABASAKQASAKAKAQQAWAhgIBCQgIA+gWBLQgNAsggBbQgPApgLAXQgSAhgYAUQgVARgqAPQg4AUgNAGQgPAIgiAXQgfAVgTAIQgkAPg0ACIhcgCgA9ylrQgwg5AAhPQAAhQAwg4QAwg5BFAAQBEAAAwA5QAxA4AABQQAABPgxA5QgwA4hEAAQhFAAgwg4gAtqlvQgeguAAhAQAAhAAegtQAfguArAAQArAAAeAuQAfAtAABAQAABAgfAuQgeAtgrAAQgrAAgfgtgAh6qsQgqhDAAhfQAAhfAqhDQAqhDA8AAQA6AAAqBDQArBDAABfQAABfgrBDQgqBDg6AAQg8AAgqhDgAKaqmQgsg2AAhMQAAhMAsg2QAsg2A9AAQA+AAArA2QAsA2AABMQAABMgsA2QgrA2g+AAQg9AAgsg2g");
	this.shape_28.setTransform(379.2757,286.5481);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#007B87").s().p("Egk5AswQjUgSigg9QjHhMiYiXQibibhEjEQgihhgXiVQgXingPhUQgMg+geiEQgdh+gLhEQgJg1gRh+QgPhzgMg/QgQhYgzi6QgxiygRhhQgbicAIiWQAHidAuiOQAwiVBZh9QBciBB7hWQAZgRALgJQASgRAHgSQAEgMABgRIgCgeIgYkFQgFg3gFgfQgHgwgLglQgLghgVgsIgkhMQhOiogNi7QgOi9A2ivQA2ixB1iTQB2iVCghZQCIhNC3gqQCIggDLgTQEXgcFggIIC6gEMA6KAABIgNAAIJiAAIAvABIAIAAIAMAAQAmACAdAGQBmAVBxBZQBrBWBRBuQBTBvAvB+QA4CXAPDIQAKB8gFDvIgNLDQgHFjACCsQAEElAYDnQAJBVAdDSQAZC8AJBsQANCcACDUQAAB7gCD1QAADjgIBjQgPC1g1CGQg2CKhpB4QhjBxiFBVQjqCWlQA8QiiAcjOAKQh5AFj6ACQovAExhAOI11ASQofAHkPACIg3AAQjTAAh2gLgAdqMzQgBAOABAcQgUAAgSALQgTAKgLARQgHALgIAZQgVA9gMArQgKAjgJAlIgGAZIgHASQgIATgDAYQgFArATAZQAJALABADQABAEgBAKQgCAiAGASQAHAXAUARQAUAQAYADQAZADAXgLQAXgMANgVQAHgLAHgXIANgkQAKAbAPAPQAOAQAVAHQAVAHAVgEQAVgEARgPQARgOAIgUQAJgWgDgsQgBgIACgFQACgGAKgJQAVgUAGgdQACgLABgPIgBgaQABgnAJg9IAPhjQAEgvgLgaQgOghgigNQghgMgiAOQgBgKgFgJIiYAAQgIARgBAYgAIKTmQAEABAHAFQAVAOAagBQAaAAAUgOQAVgOAKgYQAKgYgFgYQgFgTgOgYQASgUAFgbQAGgbgKgZQgEgKADgGIAHgGQATgLAMgSQANgSADgWQADgVgHgVQgHgVgPgPQgUgUgngNQgjgMg8gIQhMgKgVgFIg4gMQgggGgYACIACAAQgLABgKADQgZAIgPASQgHAJgEAJIgDgBQgZgIgdAAQgngBghAMQglAOgRAgQgNAXADAbIACALQgDAOABAOQACAZAOASQgJAXgBAhQgBAiAIAWQAMAhAdASQAgASAhgKIANgEQAYADAYgMQAYgMANgXQAKgTACgcIAAgyIABgkQgBgMgCgLQAKgIAHgMIAEgIIAMACQgCAXALAWQAKAWATAMQAFADABADIAAAGQgEAUAHATQAGAUAPAOQAHAHABACQABAEAAAIQgBAZABAMQACAVAGAPQAOAdAbANQAbANAfgFIAMgBIADAAgEAhJgAcQgVACgRAMQgUAOgJAWQgJAYAEAYQAFAZAVAeQAVAeAUAWIAYAZQAOAPAJALQAOASAYAoQAXAjAZAOQATAKAbAEQARACAgAAQAmAAAUgFQAfgGASgTQAIgIAJgRIAPgbQAHgKAXgYQAVgVAHgOQAGgLAFgRIAIgeQAKghAmg5QAmg5AKggQAPgrgDhQQgCg8gFhFQgCgXgDgNQgEgTgKgNQgRgZghgFQgggGgdAOQgxAZgdBFQgLAagKAlIgRBCQgQA7gXA8QgOAlgDAOIgDAgQAAAWgCAKQgGAjgVAbQgFgTgcgSQgkgXgHgIQgHgIgIgOIgNgXQgWglgngOQgPgEgOAAIgMAAgAnSj7QAGDNAoB/QBECmBFAyIALAGQBNAoBQgKQBtgTANheImvn8gASVlXQgYAKgOAWQgPAWABAZQAAANAEATIAHAfQADAPAAA0QAAApAJAYQANAdArAjQAcAWAIAOQAEAIAFAPIAHAXQALAbAcAUQAZASAgAIQAaAHAkACIA/ABIBcACQA0gBAkgQQATgIAfgVQAigWAPgIQANgHA4gTQAqgPAVgSQAYgTASghQALgWAPgqQAghaANgsQAWhMAIg+QAIhBgWghQgKgRgSgKQgSgKgTgBQgUAAgSAIQgTAJgMAQQgLAPgGAYQgEAPgEAdIgIBGQgCASgGAJQgFAIgLAFQgGADgPAEQgxAPg+AwQhdBHgMAHIhNArQgtAagYAaQgUAXgOgIQgFgDgFgNIgUg8QgMgjgLgXIgXgtQgPgcgHgSIgRgtQgKgagOgPQgSgSgagFQgJgCgJAAQgQAAgPAGgAypkzQgwA5AABPQAABQAwA4QAwA4BFAAQBEAAAwg4QAxg4AAhQQAAhPgxg5Qgwg4hEAAQhFAAgwA4gAihkCQgeAuAABAQAABAAeAtQAfAtArAAQArAAAegtQAegtAAhAQAAhAgeguQgegtgrAAQgrAAgfAtgAnVj4IADgDIAAgSIAAASgAJOqnQgqBDAABfQAABfAqBDQAqBDA8AAQA7AAAqhDQArhDAAhfQAAhfgrhDQgqhDg7AAQg8AAgqBDgAVjpiQgsA2AABMQAABMAsA2QAsA2A9AAQA+AAArg2QAsg2AAhMQAAhMgsg2Qgrg2g+AAQg9AAgsA2gAkBohIAkgEIgKhQg");
	this.shape_29.setTransform(307.9735,253.6708);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(258.8,206.2,940.2,335.00000000000006);
// library properties:
lib.properties = {
	id: '405C9CA0172DF5499686E90902AB5996',
	width: 640,
	height: 480,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_1.png", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['405C9CA0172DF5499686E90902AB5996'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;